Repository phuongthuan/forum, pull requests merged in 2018-03, with the labels that each got.

#6 Episode11: Add filter Threads
  app/Channel.php
  app/Http/Controllers/ThreadsController.php
  resources/views/layouts/app.blade.php
  routes/web.php
  tests/Feature/ReadThreadsTest.php
  tests/Unit/ChannelsTest.php
Labels: enhancement, feature

#7 Episode12: Validation error in form
  resources/views/layouts/app.blade.php
  resources/views/threads/create.blade.php
  resources/views/threads/show.blade.php
Labels: feature

#9 Episode15: Refactoring Filter Threads
  app/Filters/Filters.php
  app/Filters/ThreadFilters.php
  app/Http/Controllers/ThreadsController.php
  app/Thread.php
Labels: refactoring

#10 Episode16: Add paginate replies
  app/Http/Controllers/ThreadsController.php
  app/Thread.php
  resources/views/threads/show.blade.php
Labels: feature

#11 Episode17: Add popular threads
  app/Filters/ThreadFilters.php
  app/Http/Controllers/ThreadsController.php
  resources/views/layouts/app.blade.php
  resources/views/threads/index.blade.php
  tests/Feature/ReadThreadsTest.php
  tests/utilities/functions.php
Labels: feature

#12 Add favorites reply
  app/Favorite.php
  app/Http/Controllers/FavoritesController.php
  app/Reply.php
  database/migrations/2018_03_08_135338_create_favorites_table.php
  resources/views/threads/reply.blade.php
  routes/web.php
  tests/Feature/FavoritesTest.php
Labels: feature

#13 Add UserProfile
  app/Http/Controllers/ProfilesController.php
  app/User.php
  database/seeds/ThreadsTableSeeder.php
  resources/views/profiles/show.blade.php
  resources/views/threads/reply.blade.php
  resources/views/threads/show.blade.php
  routes/web.php
  tests/Feature/ProfilesTest.php
Labels: feature

#14 Authoriztion
  app/Http/Controllers/ThreadsController.php
  app/Policies/ThreadPolicy.php
  app/Providers/AuthServiceProvider.php
  app/Thread.php
  database/seeds/ChannelsTableSeeder.php
  resources/views/layouts/app.blade.php
  resources/views/layouts/nav.blade.php
  resources/views/profiles/show.blade.php
  resources/views/threads/index.blade.php
  resources/views/threads/show.blade.php
  routes/web.php
  tests/Feature/CreateThreadsTest.php
Labels: feature

#15 Big Big feature, Activity polymorphic relationship
  app/Activitable.php
  app/Activity.php
  app/Reply.php
  app/Thread.php
  database/migrations/2018_03_09_112341_create_activities_table.php
  database/seeds/RepliesTableSeeder.php
  database/seeds/ThreadsTableSeeder.php
  tests/Unit/ActivityTest.php
Labels: enhancement

#16 Episode 26+27
  app/Activitable.php
  app/Activity.php
  app/Favoritable.php
  app/Favorite.php
  app/Http/Controllers/ProfilesController.php
  app/Reply.php
  app/User.php
  resources/views/profiles/activities/activity.blade.php
  resources/views/profiles/activities/created_favorite.blade.php
  resources/views/profiles/activities/created_reply.blade.php
  resources/views/profiles/activities/created_thread.blade.php
  resources/views/profiles/activities/deleted_thread.blade.php
  resources/views/profiles/show.blade.php
  resources/views/threads/index.blade.php
  tests/Feature/ProfilesTest.php
  tests/Unit/ActivityTest.php
Labels: enhancement

#17 Fix delete activities
  app/Activitable.php
  app/Thread.php
  tests/Feature/CreateThreadsTest.php
Labels: enhancement

#19 Add delete feature for delete replies. Episode 30+31
  app/Favorite.php
  app/Http/Controllers/RepliesController.php
  app/Policies/ReplyPolicy.php
  app/Providers/AuthServiceProvider.php
  app/Reply.php
  resources/views/profiles/activities/created_favorite.blade.php
  resources/views/profiles/show.blade.php
  resources/views/threads/reply.blade.php
  routes/web.php
  tests/Feature/ParticipateInForumTest.php
Labels: enhancement

#20 authenticated users can update replies
  app/Http/Controllers/RepliesController.php
  public/js/app.js
  resources/assets/js/app.js
  resources/assets/js/components/Reply.vue
  resources/views/layouts/app.blade.php
  resources/views/profiles/activities/created_favorite.blade.php
  resources/views/threads/reply.blade.php
  routes/web.php
  tests/Feature/ParticipateInForumTest.php
Labels: enhancement

#21 Add ldelete button by VueJS
  app/Http/Controllers/RepliesController.php
  public/js/app.js
  resources/assets/js/components/Reply.vue
  resources/views/threads/reply.blade.php
  resources/views/threads/show.blade.php
Labels: enhancement

#22 Change favorite button approach by VueJS
  app/Favoritable.php
  app/Http/Controllers/FavoritesController.php
  app/Reply.php
  public/js/app.js
  resources/assets/js/components/Favorite.vue
  resources/assets/js/components/Reply.vue
  resources/views/threads/reply.blade.php
  routes/web.php
  tests/Feature/FavoritesTest.php
Labels: enhancement

#23 Fix bug favorite user activities
  app/Favoritable.php
  resources/views/profiles/show.blade.php
  resources/views/threads/reply.blade.php
Labels: bug

#24 Add Edit button Reply using VueJS
  public/js/app.js
  resources/assets/js/app.js
  resources/assets/js/components/Replies.vue
  resources/assets/js/components/Reply.vue
  resources/assets/js/pages/Thread.vue
  resources/views/layouts/app.blade.php
  resources/views/threads/show.blade.php
Labels: feature

#26 Add Vue Paginator
  app/Http/Controllers/RepliesController.php
  app/Http/Controllers/ThreadsController.php
  package-lock.json
  package.json
  public/js/app.js
  resources/assets/js/app.js
  resources/assets/js/components/NewReply.vue
  resources/assets/js/components/Paginator.vue
  resources/assets/js/components/Replies.vue
  resources/assets/js/components/Reply.vue
  resources/assets/js/mixins/collection.js
  resources/views/threads/show.blade.php
  routes/web.php
  tests/Feature/ReadThreadsTest.php
Labels: feature

#27 Add Unanswered thread filter
  app/Filters/ThreadFilters.php
  app/Reply.php
  app/Thread.php
  database/factories/ModelFactory.php
  database/migrations/2018_03_03_092814_create_threads_table.php
  database/seeds/ThreadsTableSeeder.php
  public/js/app.js
  resources/assets/js/components/Replies.vue
  resources/views/layouts/nav.blade.php
  tests/Feature/ParticipateInForumTest.php
  tests/Feature/ReadThreadsTest.php
Labels: feature
